import Navbar from "@/components/navbar/navbar";
import "./globals.css";

export const metadata = {
  title: "Sajid-Don",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased relative`}
      >
        <Navbar/>
       
        {children}
      </body>
    </html>
  );
}
